### ISSUE TITLE
Create database entities

### ISSUE THREAD

**Issue by JaredLGillespie** [SprinkleLord/card-inventory-backend#4]
_Creation of entity framework database entities_
- Create entity objects
- Add Entity Framework to project

**Comment by JaredLGillespie** [comment]
@calebpayton  is this done?

**Comment by calebpayton** [comment]
Yes

On Oct 10, 2017 6:07 PM, "Jared Gillespie" <notifications@github.com> wrote:

@calebpayton <https://github.com/calebpayton> is this done?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SprinkleLord/card-inventory-backend/issues/4#issuecomment-335622778>,
or mute the thread
